spring:
  datasource:
    url: jdbc:mysql://localhost:53306/spring_boot_querydsl
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
